######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 11 13:04:27 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += widget.h \
    cutScreen.h \
    inputdialog.h
FORMS += widget.ui
SOURCES += main.cpp widget.cpp \
    cutScreen.cpp \
    inputdialog.cpp

RESOURCES += \
    pic.qrc

RC_FILE = app.rc
